### ISSUE TITLE
!roll is broken again

### ISSUE THREAD

**Issue by bbriggs** [bbriggs/Legobot#57]
Input:
`lemming | !roll 20`

Error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/briggsb/Legobot/Legobot/Lego.py", line 23, in run
    self.handler(self.message)
  File "/home/briggsb/Legobot/Legobot/Legos/Roll.py", line 12, in handle
    self.reply(message, 'You Rolled: ' + ', '.join([str(result) for result in results]))
TypeError: 'Integer' object is not iterable
```

**Comment by bbriggs** [comment]
This command should return help text on this particular input
